# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 清华大学镜像（指定下载源）
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

target 'BRNetworkDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'YTKNetwork'
  pod 'BRNetwork/Cache', :path => '../'
  

  # Pods for BRNetworkDemo

  target 'BRNetworkDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
