# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BRNetworkDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'YTKNetwork'
  pod 'BRNetwork', :path => '../'
  

  # Pods for BRNetworkDemo

  target 'BRNetworkDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
